---
server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/Test
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
